const INITIAL_STATE = {
  property: [
    {
      id: '1',
      transation: 'Comprar',
      image: [
        require('~/assets/placeholder.jpg'),
        require('~/assets/placeholder.jpg'),
        require('~/assets/placeholder.jpg'),
        require('~/assets/placeholder.jpg'),
      ],
      price: 'R$ 850,00',
      address: 'Rua Fabio Barbosa',
      number: '65',
      neighborhood: 'Belo Fabio',
      cep: '37031-215',
      city: 'Varginha',
      state: 'MG',
      specification: {
        bedroom: 4,
        bathroom: 5,
        parkingSpace: 2,
        area: 100,
      },
    },
    {
      id: '2',
      transation: 'Alugar',
      image: [
        require('~/assets/placeholder.jpg'),
        require('~/assets/placeholder.jpg'),
        require('~/assets/placeholder.jpg'),
        require('~/assets/placeholder.jpg'),
      ],
      price: 'R$ 550,00',
      address: 'Rua Gabriel Castro',
      number: '65',
      neighborhood: 'Belo Castro',
      cep: '37031-215',
      city: 'Varginha',
      state: 'MG',
      specification: {
        bedroom: 4,
        bathroom: 5,
        parkingSpace: 2,
        area: 100,
      },
    },
    {
      id: '3',
      transation: 'Comprar',
      image: [
        require('~/assets/placeholder.jpg'),
        require('~/assets/placeholder.jpg'),
        require('~/assets/placeholder.jpg'),
        require('~/assets/placeholder.jpg'),
      ],
      price: 'R$ 950,00',
      address: 'Rua Erik Silva',
      number: '65',
      neighborhood: 'Belo Erik',
      cep: '37031-215',
      city: 'Varginha',
      state: 'MG',
      specification: {
        bedroom: 4,
        bathroom: 5,
        parkingSpace: 2,
        area: 100,
      },
    },
    {
      id: '4',
      transation: 'Alugar',
      image: [
        require('~/assets/placeholder.jpg'),
        require('~/assets/placeholder.jpg'),
        require('~/assets/placeholder.jpg'),
        require('~/assets/placeholder.jpg'),
      ],
      price: 'R$ 820,00',
      address: 'Rua Juvenal Cardoso',
      number: '65',
      neighborhood: 'Belo Horizonte',
      cep: '37031-215',
      city: 'Varginha',
      state: 'MG',
      specification: {
        bedroom: 4,
        bathroom: 5,
        parkingSpace: 2,
        area: 100,
      },
    },
    {
      id: '5',
      transation: 'Comprar',
      image: [
        require('~/assets/placeholder.jpg'),
        require('~/assets/placeholder.jpg'),
        require('~/assets/placeholder.jpg'),
        require('~/assets/placeholder.jpg'),
      ],
      price: 'R$ 750,00',
      address: 'Rua Jao Bola',
      number: '69',
      neighborhood: 'Belo Jao',
      cep: '37031-215',
      city: 'Varginha',
      state: 'MG',
      specification: {
        bedroom: 4,
        bathroom: 5,
        parkingSpace: 2,
        area: 100,
      },
    },
    {
      id: '6',
      transation: 'Alugar',
      image: [
        require('~/assets/placeholder.jpg'),
        require('~/assets/placeholder.jpg'),
        require('~/assets/placeholder.jpg'),
        require('~/assets/placeholder.jpg'),
      ],
      price: 'R$ 750,00',
      address: 'Rua Juvenal Cardoso',
      number: '65',
      neighborhood: 'Belo Horizonte',
      cep: '37031-215',
      city: 'Varginha',
      state: 'MG',
      specification: {
        bedroom: 4,
        bathroom: 5,
        parkingSpace: 2,
        area: 100,
      },
    },
  ],
};

export default function Properties(state = INITIAL_STATE, action) {
  switch (action.type) {
    default:
      return state;
  }
}
